### ISSUE TITLE
h1 tag in the table of contents

### ISSUE THREAD

**Issue by EllDudley** [airpair/airpair-com-v1-issue-tracker#212] opened 2015-03-11 01:36 UTC
From Nic's post - 

https://www.airpair.com/ionic-framework/posts/ionic-firebase-password-manager

![screen shot 2015-03-10 at 19 35 12](https://cloud.githubusercontent.com/assets/857253/6588807/a43f2498-c75c-11e4-8164-ab1431b0fad7.png)

**Comment by jkresner** [comment] 2015-03-12 00:31
This looks like a duplicate of another issue you posted that I just closed. I think it's gone now :)

**Closed by jkresner** 2015-03-12 00:31 UTC
