### ISSUE TITLE
Numbers on Stack and Bookmarks look like notifications 

### ISSUE THREAD

**Issue by marsty5** [airpair/airpair-com-v1-issue-tracker#73] opened 2015-01-09 23:44 UTC
When one adds skills on his/her stack and add posts on bookmarks, a number appears on the image. It intuitively gives the impression that he/she has unseen notifications. I keep on clicking on them to make them disappear.
![airpair](https://cloud.githubusercontent.com/assets/2454869/5689227/585797d6-9859-11e4-8a21-57cdd98b4d2a.png)

**Comment by jkresner** [comment] 2015-01-11 19:59
Fair point. Will be polishing a lot of design and UX over the coming 2 weeks. I'll talk to our UX person about it this week.

**Comment by jkresner** [comment] 2015-03-11 19:58
Closing as duplicate of 

https://github.com/airpair/airpair-com-v1-issue-tracker/issues/119

Your account has been credit $10 :)

**Closed by jkresner** 2015-03-11 19:58 UTC
Labels: enhancement, ux-improvement

**Comment by marsty5** [comment] 2015-03-11 20:05
thanks! cheers!
ᐧ

On Wed, Mar 11, 2015 at 7:58 PM, Jonathon Kresner <notifications@github.com>
wrote:

> Closed #73
> <https://github.com/airpair/airpair-com-v1-issue-tracker/issues/73>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/airpair/airpair-com-v1-issue-tracker/issues/73#event-250399101>
> .
>



-- 
Maria Stylianou
Co-founder at SolidSteps <http://solidsteps.io/> and EF <http://joinef.com/>
 Alumni
@marsty5 <http://twitter.com/marsty5>, @solidstepsIO
<http://twitter.com/solidstepsio>

**Comment by jkresner** [comment] 2015-03-17 20:20
@marsty5 What do you think of the new menu system style?

**Comment by marsty5** [comment] 2015-03-23 00:10
@jkresner I like it so much more! Initially I couldn't even remember what was the problem, then I saw my printscreen and remembered. Well done nailing the UX :)

**Comment by jkresner** [comment] 2015-03-23 00:32
thank you :+1:
